[package]
name = "tinyclatd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
chrono = "0.4.38"
dbus = "0.9.7"
libc = "0.2.155"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0"
signal-hook = "0.3.17"
sysctl = "0.5.5"

[build-dependencies]
dbus-codegen = "0.11.0"
